FROM ubuntu:focal-20220531

RUN apt-get update -y 
RUN apt-get -y install git
RUN apt-get -y g++
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt-get install -y cmake && apt-get clean

COPY . /geliosphere
RUN cd /geliosphere && cmake --clean-first -DCPU_VERSION_ONLY=1 -DCMAKE_BUILD_TYPE=Release --install ./ && make

CMD ["bash"]