name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (CPU)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.22.1"
      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCPU_VERSION_ONLY=1
      - name: Build
        run: |
          cmake --build build -- -j$(nproc)
